name: CI

on:
  push:
    branches:
      - master
      - "dependabot/**"
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  test:
    name: Test on Node.js ${{ matrix.node }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
